package viabots.messageData;

public enum TopicNames {
    GUI_TOPIC,
    CONVEYOR_IN_TOPIC,
    CONVEYOR_OUT_TOPIC,
    MODELER_GUI,
    LOG_TOPIC,
    S2_TO_S1_TOPIC,
    S1_TO_S2_TOPIC,
    MODELER_NEW_BOX_TOPIC,
    S2_TO_S3_TOPIC,
    REQUESTS_TO_MODELER,
    UI_TO_MANIPULATOR,
    S3_TO_S2_TOPIC,
    S2_TO_S2_TOPIC,
    BOX_GEN_MODEL_TOPIC,
    DISABLE_PREDICTION,
    DISABLE_CONTROL,
    PARAMETERS_TOPIC,
    BOX_TIME_COUNTER_TOPIC

}
